const AUDIO_MP3_FILE_SIGNATURES = ["49 44 33", "FF FB", "FF F3"];
const AUDIO_WAV_FILE_SIGNATURES = ["52 49 46 46"];
export const AUDIO_M4A_FILE_SIGNATURES = ["66 74 79 70 4D 34 41 20"];
const AUDIO_AAC_FILE_SIGNATURES = ["41 44 49 46", "FF F1", "FF F9"];
const AUDIO_OGG_FILE_SIGNATURES = ["4F 67 67 53"];
const AUDIO_FLAC_FILE_SIGNATURES = ["66 4C 61 43"];
const AUDIO_FILE_SIGNATURES = [
  ...AUDIO_MP3_FILE_SIGNATURES,
  ...AUDIO_WAV_FILE_SIGNATURES,
  ...AUDIO_M4A_FILE_SIGNATURES,
  ...AUDIO_AAC_FILE_SIGNATURES,
  ...AUDIO_OGG_FILE_SIGNATURES,
  ...AUDIO_FLAC_FILE_SIGNATURES,
];

export default AUDIO_FILE_SIGNATURES;
